active_voice_recognition = option('random', 'pocketsphinx', 'google_speech_recognition', 'google_cloud_speech', 'wit_ai', 'bing', houndify', 'ibm', default='google_speech_recognition')
google_speech_recognition_api_key = string(default='')
google_cloud_speech_json_credentials = string(default='')
wit_ai_api_key = string(default='')
bing_api_key = string(default='')
houndify_client_id = string(default='')
houndify_client_key = string(default='')
ibm_speech_to_text_username = string(default='')
ibm_speech_to_text_password = string(default='')
